#pragma once

typedef void(* PINATA_PATCH_mldsa_sign_start_callback_t)();
typedef void(* PINATA_PATCH_mldsa_sign_finish_callback_t)();

extern PINATA_PATCH_mldsa_sign_start_callback_t PINATA_PATCH_mldsa_start_callback;
extern PINATA_PATCH_mldsa_sign_finish_callback_t PINATA_PATCH_mldsa_finish_callback;

PINATA_PATCH_mldsa_sign_start_callback_t PINATA_PATCH_mldsa_set_sign_start_callback(PINATA_PATCH_mldsa_sign_start_callback_t f);
PINATA_PATCH_mldsa_sign_finish_callback_t PINATA_PATCH_mldsa_set_sign_finish_callback(PINATA_PATCH_mldsa_sign_finish_callback_t f);
