on:
  push:
    branches:
    - main
    paths-ignore:
    - README.md
  pull_request:
    branches:
    - main
    paths-ignore:
    - README.md

jobs:
  ubuntu:
    runs-on: ubuntu-latest

    steps:
      # Install system packages.
      - name: Install system packages
        run: sudo apt-get update && sudo apt-get install gcc-arm-none-eabi ninja-build libssl-dev libgtest-dev libboost-dev dfu-util

      # Checkout the repository.
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      # Compile firmware.
      - name: Configure firmware
        run: cmake -DCMAKE_TOOLCHAIN_FILE=gcc-arm-none-eabi.toolchain.cmake -DCMAKE_INSTALL_PREFIX=$(pwd)/build/firmware -GNinja -S. -Bbuild
      - name: Build firmware
        run: cmake --build ./build
      - name: Prepare firmware
        run: cmake --build ./build --target install

      # Compile test driver.
      - name: Configure test runner
        run: cmake -DCMAKE_BUILD_TYPE=Debug -SPinataTests -BPinataTests/build -GNinja
      - name: Build test runner
        run: cmake --build ./PinataTests/build
